##########################################################################
## Script to run a test Python I/O script with a Singularity container
##########################################################################

### queue method
#PBS -q debug

### resources
#PBS -l select=1:ncpus=28:mem=168gb:pcmem=6gb

### project name
#PBS -N python_io_sing

### group name
#PBS -W group_list=ktmorz

### can node be shared?
#PBS -l place=pack:shared

### CPUtime required in hhh:mm:ss.
### Leading 0's can be omitted e.g 48:0:0 sets 48 hours
#PBS -l cput=00:28:00

### walltime before job is cut off
#PBS -l walltime=00:01:00

### set up path
DATADIR=/xdisk/spalding/
cd $DATADIR

### Command to run the script within the Singularity container
### (N.b. container must already be built, and be in /xdisk/)

# QUESTIONS:
- AM I BINDING THESE VOLUMES CORRECTLY, GIVEN IT SHOULD BE RELATIVE TO XDISK?

### run Singularity container
singularity exec --bind ${HOME}/lbti_altair_fizeau/modules:/modules --bind /vol_c:/vol_c [CONTAINER NAME].simg python python_io_test.py
