### Your job will use 1 node, 28 cores, and 168gb of memory total.
#PBS -q standard
#PBS -l select=1:ncpus=28:mem=168gb:pcmem=6gb
### Specify a name for the job
#PBS -N test_python_io
### Specify the group name
#PBS -W group_list=ktmorz
### Used if job requires partial node only
#PBS -l place=pack:shared
### CPUtime required in hhh:mm:ss.
### Leading 0's can be omitted e.g 48:0:0 sets 48 hours
#PBS -l cput=00:28:00
### Walltime is how long your job will run
#PBS -l walltime=00:01:00

python3 python_io.py
