#PBS -q debug
#PBS -l select=2:ncpus=28:mem=168gb:pcmem=6gb
### Specify a name for the job
#PBS -N cpu_count_debug
### Specify the group name
#PBS -W group_list=ktmorz
### Sharing settings
#PBS -l place=free
### CPUtime required in hhh:mm:ss.
### Leading 0's can be omitted e.g 48:0:0 sets 48 hours
#PBS -l cput=00:56:00
### Walltime is how long your job will run
#PBS -l walltime=00:01:00
### send email when done
#PBS -M spalding@email.arizona.edu

### load python 3.6.5
module load python/3

### get current directory
export start_dir=$PWD

### make a new /tmp/ directory on the compute node
rm -fr /tmp/$USER
mkdir /tmp/$USER

### copy script into the /tmp/ directory on the same node
cp /xdisk/spalding/cpu_count_test.py /tmp/$USER
cd /tmp/$USER

### run
python cpu_count_test.py

### move back to start directory
cd start_dir

echo "Back in start directory"
